### ISSUE TITLE
boolean values being treated as strings

### ISSUE THREAD

**Issue by megamay79** [nikku/camunda-worker-node#12]
I've was trying to use a boolean value in the variables for the complete task method and it was being turned into a json string. I'm not sure if there is another way that to work with booleans that wouldn't require a change, but I added two lines of code to workers.js to handle the case where the type is boolean. 
this is what I have now for the last if statement of the getSerializedType method:

if (typeof value === 'number') {
      type = 'Double';
    } else if(typeof value === 'boolean') {
        type = 'Boolean';
    }else{
      type = 'String';
    }

**Comment by nikku** [comment]
Thanks for reporting!

Your fix looks good. Seems like we simply forgot about boolean type variables :cry:.

**Comment by nikku** [comment]
Released the bug fix for this with `v4.0.1`.

**Comment by megamay79** [comment]
Thanks. That was fast.

**Comment by nikku** [comment]
You're welcome.
