### ISSUE TITLE
How can I prevent the completion of a task?

### ISSUE THREAD

**Issue by zailic** [nikku/camunda-worker-node#13]
hi @nikku, 
Thank you for sharing this excellent lib.
Though, going through your samples, is not clear to me how can I "skip" a task for being completed:
```javascript
workers.registerWorker('work:A', [ 'numberVar' ], async function(context) {
  
  // let say, my business logic tells here that the current task is not ready
  // to be completed and I would like to postpone it for the next iteration
  // It is possible to do that?

  // complete with update variables
  return {
    variables: {
      numberVar: newNumber
    }
  };
});
```
Thanks, 
Ionut

**Comment by nikku** [comment]
You're essentially asking for the _unlock_ feature. 

What exactly is the reason you'd like to wait? Polling the database or a message queue whether work was done?

An alternative would be to make your task long-running in these cases:

```javascript
workers.registerWorker('work:a', async function(context) {

  let completed = false;

  while (true) {
    completed = await didWorkComplete();

    if (completed) {
      break;
    }

    // extend the lock for another five seconds
    await extendLock(5000);

    // wait for arbitrary delay
    await delay(5000);
  }

  return {
    variables: { ... }
  }
});

**Comment by nikku** [comment]
Throwing an error would work, too:

```javascript
workers.registerWorker('work:a', async function(context) {
  throw new Error('not completed yet');
});
```

**Comment by zailic** [comment]
Well in my scenario, is a "message" which can be expected to be ready up to several hours/days since the process was started,  so throwing an error can be an approach.
Thanks for your quick replay!

**Comment by nikku** [comment]
Closing this as things are sorted out I suppose.
