### ISSUE TITLE
start-workers will error in a Windows environment

### ISSUE THREAD

**Issue by Flazzarious** [nikku/camunda-worker-node#16]
Minor issue for Windows users...

When trying to start the example workers in a Windows environment the syntax in example/package.json `DEBUG=orderProcess:*,worker,worker:*`
will cause Node to error.  The fix it to remove this from the package.json and set it in the shell.

For Windows PowerShell it would be:
`$Env:DEBUG="orderProcess:*,worker,worker:*"`

Thanks!
Aaron

**Comment by nikku** [comment]
For cross platform compatibility we should use [cross-env](https://www.npmjs.com/package/cross-env).

I'm happy to accept a PR that integrates it.
