### ISSUE TITLE
Import fails in ReactJS project created by CRA

### ISSUE THREAD

**Issue by smonami** [nikku/camunda-worker-node#17]
Failed to compile.

```
./node_modules/camunda-worker-node/lib/worker.js
Module parse failed: Unexpected token (453:4)
You may need an appropriate loader to handle this file type.
|
|   this.options = {
|     ...this.options,
|     ...newOptions
|   };
```

**Comment by nikku** [comment]
What is _CRA_?

**Comment by smonami** [comment]
:-) Sorry, I should have mentioned it clearly at the first place. I meant ReactJS app created by creat-react-app(CRA) command line utility.

**Comment by nikku** [comment]
Could you provide me with the command line instructions to bootstrap the app and integrate this library? I'd like to reproduce this.

As far as I know create-react-app supports ES6 + Object rest spread (the syntax pasted above).

**Comment by nikku** [comment]
In NodeJS object rest/spread is available since NodeJS v8.6.0. Make sure you use the proper NodeJS version.

**Comment by smonami** [comment]
I am using NodeJS v10.1.0.

Steps to reproduce:
   1.) create-react-app test-camunda-worker  (assuming you have installed create-react-app)
   2.) cd test-camunda-worker
   3.) yarn add camunda-worker-node
   4.) In file App.js, try add :
           import { Worker }  from 'camunda-worker-node';
            Also tried default import style without {} but same result.
    5.) Yarn start

This will give you error in terminal and browser both.

**Comment by nikku** [comment]
The library, as it is right now is not ment to be used in a browser environment. 

The reason that you fail to consume it in a create-react-app bootstrapped application is that `App.js` is bundled for the browser; this is where the error originates.

I could technically ship a version that works in the browser, too. What would be the use-case though?
