### ISSUE TITLE
cannot set new variable wihtin a Service Task

### ISSUE THREAD

**Issue by Geraldf** [nikku/camunda-worker-node#18]
Hi nikku,
I cannot get my head arround, how to set a new variable in a Servcie Task, so that I can use this variable later in a Gateway Output. 
Any ideas how to do that with Camunda-Worker-Node?

**Comment by nikku** [comment]
What did not work about the basic example shown in the [Usage section](https://github.com/nikku/camunda-worker-node#usage)? If you're trying to accomplish something else, what is it?
