### ISSUE TITLE
Fetch all context variables by default

### ISSUE THREAD

**Issue by mrfelton** [nikku/camunda-worker-node#3]
The default behavior of Camunda is to return all variables from the context when calling fetchAndLock unless you specifically ask for a subset of them:

> variables	A JSON array of String values that represent variable names. For each result task belonging to this topic, the given variables are returned as well if they are accessible from the external task's execution. If not provided - all variables will be fetched.

https://docs.camunda.org/manual/7.6/reference/rest/external-task/fetch/

With the current implementation in this package you have to explicit list the variables that you want included when registering the task worker. If no variables are listed, no context variables are returned. This makes it impossible to get all of the context variables without explicitly listing them all yet it is unlikely that a task will know the name of every single variable that exists in the process instance context.

**Comment by nikku** [comment]
That is correct. Why would you "wildcard" download all variables in a task? Doesn't the task always depend on a very specific defined set of variables?

**Comment by mrfelton** [comment]
> Doesn't the task always depend on a very specific defined set of variables?

It is possible for tasks to be dynamic in nature, with their specific behaviour being determined by the results of previous tasks or things that are completely external to the Process Instance all together.

I don't think it's right to assume that a task will always depend on a very specific predefined set of variables, or that the task will know specifically which variables it will want to deal with upfront.

Fetching all variables from the Process Instance context when performing `fetchAndLock` (wildcard) is the default behaviour of the Camunda REST api, and the ability to limit which ones are fetched is an optional feature.

I can't think of many examples where you would not want your task to have full knowledge about the context in which it is running, though I'm sure there are some.
