### ISSUE TITLE
Camunda via docker

### ISSUE THREAD

**Issue by ccristian** [nikku/camunda-worker-node#8]
"You need a Camunda BPM REST API exposed on localhost:8080/engine-rest for the tests to pass. An easy way to get it up running is via Docker."

I did that but is seems there is not engine-rest available...

**Comment by nikku** [comment]
You got trouble setting up the Camunda REST Api? How is that an issue of this project?

**Comment by ccristian** [comment]
Well I did install camunda via docker as is recommended here and the rest-api is not working.
True is not a problem of this project so please close it if you consider.If addtional steps are needed beside install&running the docker image to enable rest api woud be nice to have a comment somwhere.Cheers

**Comment by ccristian** [comment]
I got an answer here https://docs.camunda.org/manual/7.8/reference/rest/execution/
